### ISSUE TITLE
ecn is ok above 2.5Mbits usually

### ISSUE THREAD

**Issue by dtaht** [hkbakke/tc-gen#1]
While this is very clean code compared to how "sqm-scripts" has evolved (see that or "wondershaper must die") I wanted to clarify that ecn on egress is generally ok at speeds above, say, 2.5 or 4Mbits.

**Comment by dtaht** [comment]
see also: https://www.bufferbloat.net/projects/codel/wiki/CakeTechnical/

**Comment by hkbakke** [comment]
Thank you for your input! Implemented in 46a4125

In the use case where we have multiple classes, I used the ceil rate to decide if ECN should be enabled or not, based on the assumption that this is the rate it would most often run at. Would it be better to use the total up rate for the shaper or even only the guaranteed rate for the class for this?

**Comment by dtaht** [comment]
ECN marked packets "have mass", and cause side-effects in codel on non ecn-marked packets, potentially pushing them out of even a fq_codel'd queue system. An un-responsive sender like TCP BBR presently is can lead to really bad results, per this thread here:

https://groups.google.com/forum/#!topic/bbr-dev/VNUBKAeJSdc

example:

http://blog.cerowrt.org/flent/bbr-comprehensive/bbr_ecn_eventually_starving_ping.png

That said, ECN is like catnip for congestion control theorists, it's awesome for many sorts of flows, particularly on long delay paths and inside of vpns, (see thread above). Since it mostly works and generally helps more than it hurts, I've encouraged people to leave it on where appropriate. As bandwidths go up and up past this low (3mbit) bar, the potential for damage becomes less.

I'd configure it on/off as a function of rate for the class not the total shaper. If you have a specific voice class or background class, I'd leave it off entirely. (and not worry about BBR's current lack of ECN response curve (BBR has other issues with codel, too, but it's pretty neat)). Where ECN is deployed today is primarily on iOS and OSX against sane senders, and in data centers as part of DCTCP.

Please note that I AM opinionated and not necessarily in the majority on this topic, although trying to break my catnip addiction.

**Comment by hkbakke** [comment]
Actually "greater than 3" means "greater than or equal to 4 mbit/s" in my script because it works with bash which out of the box do not support float calculations. I think I will change the function to represent this although the result is the same. 

I have not found anything conclusive about when ECN makes more sense than turning it off, so I'll just base this on your experience. My own testing and production systems are exclusively higher bandwith symmetrical links (20 to 500 mbit/s), hence why my script only cares about mbit/s values and CPU usage and turning ECN on or off have made pretty much no difference in my usage scenarios.
