### ISSUE TITLE
flowid setting invalid

### ISSUE THREAD

**Issue by ToxicBakery** [hkbakke/tc-gen#2]
This may not be an issue for all linux distros however using alpine I am having an issue with the flowid setting when configuring the download.

```
What is ":1"?
Usage: ... u32 [ match SELECTOR ... ] [ link HTID ] [ classid CLASSID ]
               [ action ACTION_SPEC ] [ offset OFFSET_SPEC ]
               [ ht HTID ] [ hashkey HASHKEY_SPEC ]
               [ sample SAMPLE ] [skip_hw | skip_sw]
or         u32 divisor DIVISOR

Where: SELECTOR := SAMPLE SAMPLE ...
       SAMPLE := { ip | ip6 | udp | tcp | icmp | u{32|16|8} | mark }
                 SAMPLE_ARGS [ divisor DIVISOR ]
       FILTERID := X:Y:Z

NOTE: CLASSID is parsed at hexadecimal input.
./tc-gen: Error in line 418 (exit code 1)
```

This can be quickly tested with the following Dockerfile
```
FROM alpine:3.7

RUN apk add --update --no-cache openssl ca-certificates git bash make iproute2 \
    && (wget -q -O sivel-speedtest https://github.com/sivel/speedtest/releases/download/v0.0.2/speedtest_linux_amd64 && chmod +x sivel-speedtest) \
    && (git clone  https://github.com/magnific0/wondershaper.git && cd wondershaper && make install) \
    && (wget -q -O tc-gen https://raw.githubusercontent.com/hkbakke/tc-gen/master/src/tc-gen && chmod +x tc-gen)

CMD ./tc-gen -i eth0 -u 10 -d 10 \
    && ./sivel-speedtest
```

```
sudo docker build -t speedtest-cli .
sudo docker run -it --cap-add=ALL speedtest-cli
```

Removing the offending line does allow the script to execute properly however the 10Mbit setting does not seem to be properly applied to the download resulting in ~1Mbit instead. The upload value of 10Mbit results in speed tests around 9Mbit so I believe that is working nominally.

**Comment by hkbakke** [comment]
The flowid part is not really needed, but I thought it was clean to add it to it's own class, but since there seem to be some versions that do not support it I pushed a commit that removes it.

Now, tc ingress policing is difficult in many cases, and even more so in a virtualized or containerized environment. If you do not ensure that the policer sees every packet on its own by disabling GRO and any other packet aggregation mechanisms, often in the entire stack, including the host, it will not be able to calculate things correctly. Also, you need to calculate the burst size properly (se the tc-gen help) for any kind of precision. Using ifb and shape ingress is much more effective in such an environment in my experience as it often works out-of-the-box without digging through the entire stack and calculating burst size etc. Example: `tc-gen -i eth0 -u 10 -d 10 -f ifb0`, but it requires that the ifb module is available within your alpine enviroment.

But first, verify that the ingress policer is even working by running `tc-gen -i eth0` and look at the `Filters` section. Verify that the police rate is correctly set and that the rule is hit and has a success counter that follows the rule hit count (unless you have exempted traffic manually)

**Comment by ToxicBakery** [comment]
As Alpine lacks the ifb0 module I expected this to not work in general. I see your change removing flowid does resolve the main described issue though so I'll go ahead and close this. Thank you for the help!
